### ISSUE TITLE
outDir should be a full path

### ISSUE THREAD

**Issue by davezuko** [TechnologyAdvice/genesis-core#19]
* Will allow genesis-core to be used to compile JS files inside of other projects
* consider dropping srcDir

**Comment by levithomason** [comment]
What would replace `srcDir` in this scenario?

**Comment by davezuko** [comment]
@levithomason likely just having an `entry` file; no need for `srcDir` at all in that context.

What I'm _thinking_ is that genesis-core should just build input files -> output files. It's nice to have it make some assumptions about project structure, but that limits its utility in multiple compilation scenarios. It can work fine for multiple apps, assuming they are all structured the same way, but it doesn't do so well for multiple entry points that could be _anywhere_. Imagine trying to use it in a scenario like technologyadvice.com, where we have a bunch of source JS files that need to be output to a location that is not a sibling of the project's `basePath` or `srcDir`.

Then, this is where `genesis` or `genesis-cli` would come in, and it would wrap this slightly lower-level configuration with an abstraction targeted at more macro-level concepts like "a web app project" or "a multi-app project", etc.

**Comment by davezuko** [comment]
This has been done. You can now specify `--out` to the `build` task.
