### ISSUE TITLE
web-app: Consider making bundle splitting optional

### ISSUE THREAD

**Issue by levithomason** [TechnologyAdvice/genesis-core#22]
If you're building a browser extension and using genesis output as `content_scripts` in your `manifest.json`, then Chrome automatically executes these scripts on the page.

When bundle splitting is in play, Webpack tries to make requests for the emitted chunks. However, the chunks do not exist on the host, that page belongs to someone else.

Instead, it would be ideal in this case to have a single bundle that executes the app immediately and makes no requests for any chunks.

**Comment by davezuko** [comment]
Sounds good to me. I'd like to make this a single boolean if possible so that it doesn't lead to complex configurations.

**Comment by levithomason** [comment]
Agree completely.  As simple as possible, default `true` as well.

**Comment by levithomason** [comment]
I'm wondering if there is need for another target here completely.  Extensions are kind of like desktop and mobile apps, the app is stored locally so there are no requests to obtain the source.  I'm not convinced, but there may be some kind of target that captures this idea.

**Comment by davezuko** [comment]
Resolved with https://github.com/TechnologyAdvice/genesis-core/pull/28.
